import "@/styles/globals.css";

import { useState } from 'react';

import Header from '../Componentes/Header';

import Head from "next/head";

export default function App({ Component, pageProps }) {

  const claro = 'light';
  const escuro = 'dark';

  const [estilo, setEstilo] = useState(false);

  function alterarEstilo() {

    setEstilo(!estilo)

  }

  return (
    <>
      <Head>
        <title>Game Explorer</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/assets/icons8-controle-50.png" />
      </Head>

      <div className={`body ${estilo ? escuro : claro}`}>

        <Header
          imagemBotao={estilo}
          estilo={estilo ? claro : escuro}
          trocarEstilo={alterarEstilo}
        />
        <Component {...pageProps} />;

      </div>
    </>
  )


}
